package com.urlshortener.domain.entity;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import jakarta.persistence.*;
import lombok.*;

/**
 * JPA entity representing an authenticated user of the application.
 *
 * <p>Implements {@link UserDetails} directly so that Spring Security can use this entity as the
 * authentication principal without an intermediate DTO conversion layer. This means the object
 * injected via {@code @AuthenticationPrincipal} in controllers is the same entity that is stored in
 * the database.
 *
 * <p>Primary key is a UUID generated by the database ({@link GenerationType#UUID}) which avoids
 * sequential-ID enumeration attacks while still allowing efficient indexed lookups.
 */
@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User implements UserDetails {

  /**
   * Surrogate primary key. UUID is generated by the database at insert time, not by the
   * application, to avoid collisions in distributed deployments.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.UUID)
  private UUID id;

  /** Login identifier — must be unique across all accounts. */
  @Column(unique = true, nullable = false)
  private String email;

  /**
   * BCrypt-hashed password. The plain-text password is never stored. Hashing is performed by {@link
   * com.urlshortener.service.AuthService} before the entity is persisted.
   */
  @Column(nullable = false)
  private String password;

  /** Display name chosen by the user at registration. */
  @Column(nullable = false)
  private String username;

  /**
   * Authorization role. Stored as a string in the DB for readability. Defaults to {@link Role#USER}
   * for all new accounts; {@link Role#ADMIN} would be assigned manually or via an admin endpoint.
   */
  @Enumerated(EnumType.STRING)
  @Column(nullable = false)
  @Builder.Default
  private Role role = Role.USER;

  /**
   * Soft-disable flag. When {@code false}, login attempts are rejected with a {@code 401 Disabled}
   * error. Defaults to {@code true} so accounts are active immediately after registration.
   */
  @Column(nullable = false)
  @Builder.Default
  private boolean enabled = true;

  /** Automatically populated by Hibernate on first insert. */
  @CreationTimestamp
  @Column(name = "created_at", updatable = false)
  private LocalDateTime createdAt;

  /** Automatically updated by Hibernate on every flush. */
  @UpdateTimestamp
  @Column(name = "updated_at")
  private LocalDateTime updatedAt;

  // ---- UserDetails contract ----

  /**
   * Returns the email address as the Spring Security principal identifier.
   *
   * <p>{@link UserDetails#getUsername()} must return the value used as the JWT subject so that
   * {@link com.urlshortener.security.JwtAuthenticationFilter} can call
   * {@link com.urlshortener.security.UserDetailsServiceImpl#loadUserByUsername(String)} with the
   * same value that was encoded into the token at login time. Because {@code UserDetailsServiceImpl}
   * looks users up by email, this method must return the email — not the display name.
   *
   * <p>Lombok would normally generate {@code getUsername()} from the {@code username} field; this
   * explicit override takes precedence and Lombok skips generating a duplicate.
   * Use {@link #getDisplayName()} to obtain the human-readable display name instead.
   *
   * @return the user's email address (login identifier)
   */
  @Override
  public String getUsername() {
    return email;
  }

  /**
   * Returns the human-readable display name chosen at registration.
   *
   * <p>Separate from {@link #getUsername()} because the Spring Security contract requires
   * {@code getUsername()} to return the login identifier (email), not the display name.
   *
   * @return the display name stored in the {@code username} column
   */
  public String getDisplayName() {
    return username;
  }

  /**
   * Maps the user's {@link Role} to a Spring Security {@link GrantedAuthority}. The {@code "ROLE_"}
   * prefix is required by Spring Security's role-based access control conventions (e.g.
   * {@code @PreAuthorize("hasRole('ADMIN')")}).
   *
   * @return a singleton list containing the user's role as a {@link GrantedAuthority}
   */
  @Override
  public Collection<? extends GrantedAuthority> getAuthorities() {
    // Prefix "ROLE_" is required by Spring Security for role-based checks
    return List.of(new SimpleGrantedAuthority("ROLE_" + role.name()));
  }

  /**
   * Account expiry is not modelled in this application — accounts never expire on their own. Use
   * the {@link #enabled} flag to deactivate accounts instead.
   *
   * @return always {@code true}
   */
  @Override
  public boolean isAccountNonExpired() {
    return true;
  }

  /**
   * Account locking is not modelled in this application. A future enhancement could lock accounts
   * after N failed login attempts.
   *
   * @return always {@code true}
   */
  @Override
  public boolean isAccountNonLocked() {
    return true;
  }

  /**
   * Credential expiry is not modelled. Tokens are invalidated by JWT expiry rather than by
   * credential rotation tracking on the user entity.
   *
   * @return always {@code true}
   */
  @Override
  public boolean isCredentialsNonExpired() {
    return true;
  }

  /** Application-defined roles for access control. */
  public enum Role {
    /** Standard user — can create, manage, and delete their own URLs. */
    USER,
    /** Administrator — reserved for elevated access (not yet implemented). */
    ADMIN
  }
}
